Add comment out

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -27,7 +27,7 @@ jobs:
         uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
-          java-version: '11'
+          java-version: '8'
 
       - uses: actions/cache@v2
         with:
@@ -50,7 +50,7 @@ jobs:
         uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
-          java-version: '11'
+          java-version: '8'
 
       - uses: actions/cache@v2
         with:
@@ -61,25 +61,25 @@ jobs:
       - name: Test with Gradle
         run: ./gradlew test --stacktrace
 
-      - name: Get code coverage for JaCoCo
-        run: ./gradlew jacocoDevelopDebugTestReport
+#      - name: Get code coverage for JaCoCo
+#        run: ./gradlew jacocoDevelopDebugTestReport
+#
+#      - name: Upload code coverage to Codecov
+#        run: bash <(curl -s https://codecov.io/bash)
+#        env:
+#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
-      - name: Upload code coverage to Codecov
-        run: bash <(curl -s https://codecov.io/bash)
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-
-      - name: Upload test results and code coverage Artifact
-        uses: actions/upload-artifact@v2
-        if: success() || failure()
-        with:
-          name: results
-          path: |
-            **/build/reports/tests/**/*
-            **/build/reports/test-results/**/*
-            **/build/reports/jacoco/**/*
-          if-no-files-found: warn
-          retention-days: 14
+#      - name: Upload test results and code coverage Artifact
+#        uses: actions/upload-artifact@v2
+#        if: success() || failure()
+#        with:
+#          name: results
+#          path: |
+#            **/build/reports/tests/**/*
+#            **/build/reports/test-results/**/*
+#            **/build/reports/jacoco/**/*
+#          if-no-files-found: warn
+#          retention-days: 14
 
   ktlint:
     runs-on: ubuntu-latest
